using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace Kelime_Otomasyonu.Kelimeİslemleri
{
    public partial class ÖgrenilenKelimeler : DevExpress.XtraEditors.XtraForm
    {
        public ÖgrenilenKelimeler()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tbl_KelimeTableAdapter1.Fill(kelimeOtomasyonuDataSet2.tbl_Kelime);
        }

        private void ÖgrenilenKelimeler_Load(object sender, EventArgs e)
        {
            // TODO: Bu kod satırı 'kelimeOtomasyonuDataSet11.tbl_Kelime' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
            this.tbl_KelimeTableAdapter2.Fill(this.kelimeOtomasyonuDataSet11.tbl_Kelime);
            // TODO: Bu kod satırı 'kelimeDataSet.tbl_kelime' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
            this.tbl_kelimeTableAdapter.Fill(this.kelimeDataSet.tbl_kelime);
            this.Location = new Point(500, 140);
        }

        private void FillByToolStripButton_Click(object sender, EventArgs e)
        {
            try
            {
                this.tbl_kelimeTableAdapter.FillBy(this.kelimeDataSet.tbl_kelime);
            }
            catch (System.Exception ex)
            {
                System.Windows.Forms.MessageBox.Show(ex.Message);
            }

        }

        private void SorguikiToolStripButton_Click(object sender, EventArgs e)
        {
            try
            {
                this.tbl_kelimeTableAdapter.sorguiki(this.kelimeDataSet.tbl_kelime);
            }
            catch (System.Exception ex)
            {
                System.Windows.Forms.MessageBox.Show(ex.Message);
            }

        }

        private void ÖğrenilenKelimelerToolStripButton_Click(object sender, EventArgs e)
        {
            try
            {
                this.tbl_kelimeTableAdapter.ÖğrenilenKelimeler(this.kelimeDataSet.tbl_kelime);
            }
            catch (System.Exception ex)
            {
                System.Windows.Forms.MessageBox.Show(ex.Message);
            }

        }

        private void FillByToolStripButton_Click_1(object sender, EventArgs e)
        {
            try
            {
                this.tbl_KelimeTableAdapter2.FillBy(this.kelimeOtomasyonuDataSet11.tbl_Kelime);
            }
            catch (System.Exception ex)
            {
                System.Windows.Forms.MessageBox.Show(ex.Message);
            }
            lblOgrenilenKelime.Text = "BUGÜNE KADAR ÖĞRENDİĞİNİZ KELİMELER";

        }

        private void Button1_Click(object sender, EventArgs e)
        {

        }

        private void SbtnTumKelimeler_Click(object sender, EventArgs e)
        {
            Kelimeİslemleri.ÖgrenilenKelimeler klm = new Kelimeİslemleri.ÖgrenilenKelimeler();
            klm.Show();
            this.Close();
        }

        
    }
}